name: Update ICS File

on:
  # Trigger automatically every hour
  schedule:
    - cron: '0 * * * *'
  # Trigger manually via GitHub Actions UI
  workflow_dispatch:

jobs:
  run-jbang:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JBang to run Java file
      - name: Set up JBang
        uses: jbangdev/setup-jbang@main

      # Execute the cfpdev2ics.java file using JBang
      - name: Run cfpdev2ics.java
        run: jbang cfpdev2ics.java

      # Check if the .ics file was updated
      - name: Check for changes in .ics file
        run: |
          git config --global user.name 'Max Rydahl Andersen'
          git config --global user.email 'max@xam.dk'
          git commit -am "GitHub action updates"
          git push